# Generated by Django 5.2.5 on 2025-08-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_name', models.CharField(max_length=100, verbose_name='Имя ученика')),
                ('weekday', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=10, verbose_name='День недели')),
                ('lesson_time', models.TimeField(verbose_name='Время занятия')),
                ('students_phone', models.CharField(max_length=15, verbose_name='Телефон ученика')),
                ('lesson_duration', models.PositiveIntegerField(default=60, verbose_name='Продолжительность занятия (минуты)')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['weekday', 'lesson_time'],
            },
        ),
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='Файл'),
        ),
    ]
