# Generated by Django 5.2.5 on 2025-08-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_lesson_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], max_length=10, verbose_name='День недели'),
        ),
    ]
