# Generated by Django 5.2.5 on 2025-08-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lesson_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True, verbose_name='Имя страницы')),
                ('content', models.TextField(verbose_name='Содержимое страницы')),
                ('page_for', models.CharField(max_length=50, verbose_name='Для станицы')),
            ],
            options={
                'verbose_name': 'Контент страницы',
                'verbose_name_plural': 'Контент страниц',
            },
        ),
    ]
