# Generated by Django 5.2.5 on 2025-08-20 09:11

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_lesson_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержимое страницы'),
        ),
    ]
