# Generated by Django 5.2.5 on 2025-08-20 09:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pagecontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание'),
        ),
    ]
