# Generated by Django 5.2.5 on 2025-08-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_publication_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='file',
        ),
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[(0, '7 класс'), (1, '8 класс'), (2, '9 класс'), (3, '10 класс'), (4, '11 класс'), (5, 'Внеурочная деятельность'), (6, 'Разное')], default=(6, 'Разное'), max_length=100, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='publication',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний'),
        ),
        migrations.AddField(
            model_name='publication',
            name='presentation_file',
            field=models.FileField(blank=True, null=True, upload_to='publications/presentations/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='publication',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to='publications/previews/', verbose_name='Превью файл'),
        ),
    ]
