# Generated by Django 5.2.5 on 2025-08-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_publication_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.IntegerField(choices=[(0, '7 класс'), (1, '8 класс'), (2, '9 класс'), (3, '10 класс'), (4, '11 класс'), (5, 'Внеурочная деятельность'), (6, 'Разное')], default=(6, 'Разное'), verbose_name='Категория'),
        ),
    ]
