# Generated by Django 5.2.5 on 2025-09-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_publication_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='students_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя ученика'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='students_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Телефон ученика'),
        ),
    ]
