name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:          
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/v/major

            # Останавливаем службу приложения
            echo "${{ secrets.PASSWORD }}" | sudo -S systemctl stop major

            # Обновляем код из репозитория
            git pull

            # Если у вас Poetry
            /home/v/.local/bin/poetry install --no-root

            # Создаем файл .env из секрета
            echo "${{ secrets.ENV_FILE }}" > /home/v/major/.env

            # Перезапускаем systemd сервис
            echo "${{ secrets.PASSWORD }}" | sudo -S systemctl start major
